version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=usercrud
      - COMPOSE_PROJECT_NAME=usercrud
      - POSTGRES_USER=usercrud
      - POSTGRES_DB=usercrud
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  usercrud:
    image: lucasisrael/user-crud
    ports:
      - 9000:9000
    volumes:
      - ~/projects/crudusuario/application.properties:/opt/user-crud/application.properties